# This file describes a blueprint for use in Crafter Studio

# The version of this type of this file
descriptorVersion: 1

# Describe the blueprint
blueprint:
  id: org.craftercms.blueprint.headless_store
  name: Headless Store Blueprint
  tags: blueprint,website,headless,graphql
  version:
    major: 1
    minor: 1
    patch: 0
  description: |
    GraphQL-based and headless blueprint for a storefront
  website:
    name: GraphQL Headless Store Blueprint
    url: https://craftercms.org
  media:
    screenshots:
      - screenshot:
          title: Store Items
          description: Screenshot of the store items
          url: /studio/static-assets/images/blueprints/headless_store/bp_store_1.png
      - screenshot:
          title: Store Items
          description: Screenshot of the store items
          url: /studio/static-assets/images/blueprints/headless_store/bp_store_2.png
      - screenshot:
          title: Store Items
          description: Screenshot of the store items
          url: /studio/static-assets/images/blueprints/headless_store/bp_store_3.png
    developer:
      company:
        name: Crafter Software
        email: info@craftersoftware.com
        url: https://craftersoftware.com/
  build:
    id: c3d2a5444e6a24b5e0481d6ba87901d0b02716c8
    date: 2019-01-23T00:00:00Z
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  craftercmsVersionsSupported:
    - version: 3.1.0
  searchEngine: Elasticsearch
